"""转型路线内容库（策划内容，非抓取数据）。

生成逻辑：输入（当前背景 preset + 已掌握技能 + 目标岗位）→
  1) 缺口 = 目标岗位 core_skills − 已掌握技能（按数据热度排序）
  2) 8 周计划 = 该岗位 weeks 内容，且第 1-2 周按缺口重排优先级
  3) 作品集 / 简历关键词 / 面试题 = 岗位内容库
标注：本库为「策划内容」——技能优先级来自本数据集技能频次与溢价的排序，
学习资源指向公开免费材料；不代表任何招聘方官方要求。

skill id 必须与 skills_dict.py 一致。
"""

T0 = "2026-10-04"

# 当前背景预设：base_skills 为合理假设的起点技能（用户可在前端增删）
BACKGROUNDS = {
    "backend": {
        "label": "后端工程师",
        "base_skills": ["python", "docker", "sql", "python-web", "aws", "ci-cd", "linux",
                        "ml-fundamentals", "llm-fundamentals"],
    },
    "frontend": {
        "label": "前端工程师",
        "base_skills": ["javascript", "typescript", "react", "llm-fundamentals", "python"],
    },
    "data-analyst": {
        "label": "数据分析师",
        "base_skills": ["sql", "pandas", "analytics", "python", "warehouse"],
    },
    "pm": {
        "label": "产品经理",
        "base_skills": ["product-management", "user-research", "analytics", "llm-fundamentals",
                        "prompt-engineering"],
    },
    "student": {
        "label": "学生 / 应届",
        "base_skills": ["python", "ml-fundamentals"],
    },
    "sre": {
        "label": "运维 / SRE / DevOps",
        "base_skills": ["docker", "kubernetes", "linux", "terraform", "observability",
                        "ci-cd", "gcp", "aws", "llm-fundamentals"],
    },
    "data-eng": {
        "label": "数据工程师",
        "base_skills": ["sql", "spark", "airflow", "etl", "warehouse", "python", "docker",
                        "kafka"],
    },
    "ml-engineer": {
        "label": "传统 ML 工程师",
        "base_skills": ["python", "pytorch", "scikit-learn", "pandas", "docker", "ml-fundamentals",
                        "sql"],
    },
}

ROUTES = {
    # ================= LLM 应用工程师 =================
    "llm-app": {
        "pitch": "把 LLM 变成可靠的产品功能：模型调用、上下文工程、评估与降本。数据集里需求最大的通用入口岗。",
        "core_skills": ["python", "openai-api", "anthropic-api", "prompt-engineering",
                        "structured-output", "rag", "llm-eval", "function-calling",
                        "python-web", "docker", "llm-observability"],
        "nice_to_have": ["langchain", "typescript", "react", "fine-tuning", "guardrails",
                         "vector-db", "embeddings"],
        "weeks": [
            {"week": 1, "theme": "LLM 基础与 API 实战",
             "goals": ["理解 token/上下文窗口/温度/采样，能画出一次完整推理请求的生命周期",
                        "用 OpenAI/Anthropic API 各写一个最小对话应用（流式输出）",
                        "读完官方 prompt engineering 指南并整理 10 条自己的模板"],
             "deliverable": "CLI 聊天助手（支持流式、系统提示词、成本统计）",
             "resources": ["OpenAI Cookbook", "Anthropic Prompt Engineering 文档"]},
            {"week": 2, "theme": "结构化输出与函数调用",
             "goals": ["掌握 JSON mode / tool use，用 Pydantic 做输出校验与重试",
                        "实现「自然语言→结构化指令→外部 API」的小管道",
                        "了解常见失败模式（截断、幻觉字段）与防御写法"],
             "deliverable": "结构化抽取服务：发票/简历 → JSON（带校验与自愈重试）",
             "resources": ["OpenAI Function Calling Guide", "Pydantic 文档"]},
            {"week": 3, "theme": "RAG 入门",
             "goals": ["跑通 chunk → embed → 存向量库 → 检索 → 生成的完整链路",
                        "对比 3 种 chunk 策略对答案质量的影响并记录",
                        "理解 embedding 模型选择与维度/成本权衡"],
             "deliverable": "对一份 50 页 PDF 的问答机器人（可引用出处）",
             "resources": ["LlamaIndex 快速上手", "OpenAI embeddings 文档"]},
            {"week": 4, "theme": "评估（Eval）",
             "goals": ["建立 30-50 条黄金问答集，写自动评分脚本",
                        "实现 LLM-as-judge 评分 + 人工抽检对照",
                        "把 eval 接入 CI，改 prompt 必跑"],
             "deliverable": "带 eval 报告的 RAG 应用 v2（证明你改了什么、提升了多少）",
             "resources": ["OpenAI Evals", "RAGAS 文档"]},
            {"week": 5, "theme": "产品化：Web 服务与前端",
             "goals": ["用 FastAPI 包一层带鉴权/限流的 API",
                        "用 React 或 Streamlit 做可演示的前端",
                        "部署到云上，记录延迟与成本基线"],
             "deliverable": "公网可访问的 AI 应用（链接可放进简历）",
             "resources": ["FastAPI 文档", "Vercel/Streamlit Cloud"]},
            {"week": 6, "theme": "可观测与成本",
             "goals": ["接入 Langfuse/自建 tracing，记录每次调用的 token 与延迟",
                        "做缓存与模型分级（便宜模型前置、贵的兜底）",
                        "输出一份成本优化报告（优化前后对比）"],
             "deliverable": "成本下降 ≥40% 的优化记录（数据说话）",
             "resources": ["Langfuse 文档", "vLLM/推理服务概念文章"]},
            {"week": 7, "theme": "进阶：微调与本地模型",
             "goals": ["用 LoRA 微调一个小模型完成分类/抽取任务，与 prompt 方案对比",
                        "用 Ollama 跑通本地开源模型，理解量化取舍",
                        "知道什么场景该微调、什么场景不该"],
             "deliverable": "「微调 vs 提示工程」对比实验报告",
             "resources": ["Hugging Face PEFT 教程", "Ollama 文档"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["把 3 个项目整理成 GitHub README + 在线 Demo",
                        "简历植入岗位真实关键词（参考本站技能页）",
                        "模拟面试：系统设计题「设计一个文档问答 SaaS」"],
             "deliverable": "作品集网站 + 定制简历 + 面试问答准备文档",
             "resources": ["本站岗位画像", "GitHub Profile README 指南"]},
        ],
        "projects": [
            {"name": "带引用来源的文档问答（RAG）", "desc": "多格式文档接入、混合检索、答案带出处与置信度，含 eval 报告",
             "skills": ["rag", "vector-db", "embeddings", "llm-eval", "chunking"]},
            {"name": "结构化数据抽取管道", "desc": "非结构化输入→带 schema 校验的 JSON，含失败自愈与成本统计",
             "skills": ["structured-output", "function-calling", "guardrails", "python-web"]},
            {"name": "多模型路由的对话产品", "desc": "按任务复杂度路由大小模型，带 tracing 与成本看板",
             "skills": ["openai-api", "anthropic-api", "llm-observability", "react"]},
        ],
        "resume_keywords": ["LLM 应用", "RAG", "Prompt Engineering", "OpenAI/Anthropic API",
                            "Function Calling", "结构化输出", "LLM 评估/Evals", "LangChain",
                            "向量数据库", "成本优化", "Tracing/可观测"],
        "interview": {
            "technical": [
                "解释 token、上下文窗口与注意力开销的关系；长上下文的常见坑？",
                "RAG 里 chunk 大小、overlap、top-k 如何影响质量？你怎么调？",
                "如何检测并缓解幻觉？说出三种手段并给一个量化指标。",
                "Function calling 的输出不可信怎么办？设计校验与重试策略。",
                "什么时候微调优于提示工程？给出判断框架与成本对比。",
            ],
            "system_design": [
                "设计一个企业文档问答 SaaS：多租户、权限、增量索引、评估闭环。",
                "设计一个客服 AI：要求 P95 延迟 <2s、成本可控、可灰度。",
            ],
            "behavioral": [
                "讲一次你用数据说服团队改变技术方案的经历。",
                "线上 LLM 功能出过什么事故？如何复盘与预防？",
                "如何在需求模糊时定义「AI 功能做完了」的验收标准？",
            ],
        },
    },

    # ================= Agent 工程师 =================
    "agent": {
        "pitch": "让模型自主使用工具完成任务：规划、工具调用、多智能体协作与安全护栏。2025-2026 增长最快的方向。",
        "core_skills": ["agent-workflow", "function-calling", "mcp", "langgraph", "python",
                        "structured-output", "llm-eval", "guardrails", "prompt-engineering",
                        "python-web", "docker"],
        "nice_to_have": ["multi-agent", "agent-memory", "crewai", "autogen", "typescript",
                         "vector-db", "llm-observability"],
        "weeks": [
            {"week": 1, "theme": "Agent 心智模型",
             "goals": ["手写一个无框架的 ReAct 循环（思考→行动→观察）",
                        "理解 tool schema 设计：参数、描述、失败返回",
                        "读 Anthropic «Building effective agents» 并写摘要"],
             "deliverable": "200 行以内的最小可用 Agent（2 个工具）",
             "resources": ["Anthropic Building Effective Agents", "OpenAI Tool Use 文档"]},
            {"week": 2, "theme": "工具生态与 MCP",
             "goals": ["实现 5 个真实工具：搜索、代码执行、文件、数据库、HTTP",
                        "把其中一个工具封装成 MCP server 并接入 Claude/其他宿主",
                        "设计工具错误处理：重试、降级、超时"],
             "deliverable": "带 MCP server 的工具箱（可复用）",
             "resources": ["MCP 规范与 SDK", "LangChain Tools 文档"]},
            {"week": 3, "theme": "状态、记忆与工作流",
             "goals": ["用 LangGraph 或手写状态机实现多步任务编排",
                        "实现短期记忆（对话）与长期记忆（向量/KV）",
                        "处理循环、死锁与预算耗尽"],
             "deliverable": "多步研究型 Agent：给主题→产出带引用的报告",
             "resources": ["LangGraph 文档", "How to build memory systems（公开博客）"]},
            {"week": 4, "theme": "评估与可靠性",
             "goals": ["构建任务成功率基准（20+ 任务），自动跑分",
                        "分析失败案例分类：工具错、规划错、幻觉、环境",
                        "加入护栏：输出校验、危险操作确认、沙箱执行"],
             "deliverable": "Agent eval 看板（成功率/步数/成本三曲线）",
             "resources": ["RAGAS/自建 eval 脚手架", "E2B 沙箱文档"]},
            {"week": 5, "theme": "多智能体与人类在环",
             "goals": ["实现 planner-executor 双角色协作",
                        "加入人类审批节点（高危操作暂停）",
                        "对比单 Agent 与多 Agent 的成本/成功率"],
             "deliverable": "可在审批模式下安全运行的编码/运维 Agent",
             "resources": ["AutoGen/CrewAI 示例库", "Human-in-the-loop 模式文章"]},
            {"week": 6, "theme": "工程化部署",
             "goals": ["用 FastAPI 暴露 Agent 为流式服务（SSE）",
                        "容器化部署，隔离工具执行环境（沙箱）",
                        "接入 tracing：每步决策可回放"],
             "deliverable": "公网可用的 Agent 服务 + 回放调试界面",
             "resources": ["FastAPI SSE", "Docker 沙箱实践"]},
            {"week": 7, "theme": "真实场景攻坚",
             "goals": ["选一个真实任务（如自动整理简历/监控工单）端到端落地",
                        "优化：提示词压缩、缓存、并行工具调用",
                        "写复盘：失败率从 X% 到 Y% 的过程"],
             "deliverable": "真实任务自动化案例（有前后数据）",
             "resources": ["LangSmith/Langfuse tracing 案例"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["作品集：3 个 Agent 项目 + eval 数据",
                        "简历关键词对齐本站 Agent 画像高频技能",
                        "模拟系统设计：设计一个公司内部 IT 工单 Agent"],
             "deliverable": "作品集 + 面试准备文档",
             "resources": ["本站画像页", "Agent 面试真题整理（社区）"]},
        ],
        "projects": [
            {"name": "深度研究 Agent", "desc": "规划→多源检索→交叉验证→带引用报告，含成功率基准",
             "skills": ["agent-workflow", "function-calling", "rag", "llm-eval"]},
            {"name": "MCP 工具服务器", "desc": "把公司内部系统封装为 MCP 工具，含鉴权与审计日志",
             "skills": ["mcp", "structured-output", "python-web"]},
            {"name": "带审批的运维 Agent", "desc": "高危命令人工确认、沙箱执行、全链路可回放",
             "skills": ["guardrails", "docker", "multi-agent", "llm-observability"]},
        ],
        "resume_keywords": ["AI Agent", "Agentic Workflow", "MCP", "Function Calling",
                            "LangGraph", "Multi-Agent", "Human-in-the-loop", "Tool Use",
                            "Agent 评估", "沙箱执行", "LangSmith/Langfuse"],
        "interview": {
            "technical": [
                "手写 ReAct 循环：如何防止无限循环与预算失控？",
                "工具描述写得好与差的区别？举一个你优化工具 schema 的例子。",
                "MCP 解决了什么问题？与直接 function calling 的取舍？",
                "多智能体什么时候比单 Agent 好？给出反例。",
                "如何评估一个非确定型 Agent？成功率之外还要看什么？",
            ],
            "system_design": [
                "设计公司内部 IT 工单 Agent：权限、审计、失败兜底。",
                "设计一个能操作浏览器的自动化 Agent：沙箱、限速、人工接管。",
            ],
            "behavioral": [
                "你的 Agent 最离谱的一次翻车是什么？改了什么？",
                "如何向非技术干系人解释 Agent 的不确定性？",
                "讲一次你在「自动化程度 vs 可控性」之间的权衡。",
            ],
        },
    },

    # ================= RAG 工程师 =================
    "rag": {
        "pitch": "让模型答得准、答得有据：检索质量是 RAG 产品 80% 的战场。数据集显示 RAG 技能溢价 +11%。",
        "core_skills": ["rag", "vector-db", "embeddings", "chunking", "semantic-search",
                        "reranking", "doc-pipeline", "llm-eval", "rag-eval", "python",
                        "elasticsearch"],
        "nice_to_have": ["llama-index", "langchain", "pgvector", "qdrant", "knowledge-base",
                         "sql", "docker"],
        "weeks": [
            {"week": 1, "theme": "检索基础",
             "goals": ["实现 BM25 关键词检索与向量检索，理解各自盲区",
                        "掌握 embedding 模型评测（MTEB 思路）",
                        "搭建最小 RAG：单文档、固定 chunk"],
             "deliverable": "两种检索的对比笔记 + 最小 RAG demo",
             "resources": ["Elasticsearch 向量检索文档", "Sentence-Transformers 文档"]},
            {"week": 2, "theme": "文档处理管线",
             "goals": ["处理 3 种格式：PDF（表格）、HTML、Markdown",
                        "实现结构感知 chunk：标题层级/表格/代码块不切碎",
                        "建立文档解析质量的自动检查"],
             "deliverable": "鲁棒的文档接入管道（失败可重试、可观测）",
             "resources": ["Unstructured / LlamaIndex Readers"]},
            {"week": 3, "theme": "混合检索与重排",
             "goals": ["实现 hybrid search（BM25+向量+RRF 融合）",
                        "接入 cross-encoder 重排，量化收益",
                        "调参：top-k、候选集大小、重排阈值"],
             "deliverable": "检索质量提升报告（recall@k / MRR 前后对比）",
             "resources": ["Cohere Rerank / BGE-reranker", "RRF 论文"]},
            {"week": 4, "theme": "查询理解与改写",
             "goals": ["实现 query 改写/扩展/HyDE",
                        "多轮对话中的指代消解（查询重写）",
                        "元数据过滤与权限过滤"],
             "deliverable": "多轮对话问答 demo（能追问）",
             "resources": ["HyDE 论文", "LlamaIndex query transforms"]},
            {"week": 5, "theme": "评估体系",
             "goals": ["构建检索 eval（golden set + recall/MRR）",
                        "构建生成 eval（忠实度/答案相关性，RAGAS）",
                        "端到端回归测试进 CI"],
             "deliverable": "RAG 评估看板（改一版必跑）",
             "resources": ["RAGAS 文档", "TruLens/自建"]},
            {"week": 6, "theme": "规模与工程化",
             "goals": ["向量库选型实操：pgvector vs 专用库（10万级数据）",
                        "增量索引与删除同步",
                        "延迟优化：缓存、量化索引（HNSW 参数）"],
             "deliverable": "10 万级文档的检索服务（P95 < 500ms）",
             "resources": ["pgvector / Qdrant 性能调优文档"]},
            {"week": 7, "theme": "高级模式",
             "goals": ["GraphRAG 思路：实体抽取+关系检索小实验",
                        "多模态 RAG：图片/表格问答",
                        "Agentic RAG：让模型决定检索策略"],
             "deliverable": "一种高级模式的最小可行实现",
             "resources": ["GraphRAG 概述", "ColBERT/多向量检索"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["作品集：RAG 项目三件套 + 评估数据",
                        "简历对齐画像页高频技能",
                        "面试演练：从 0 设计企业知识库系统"],
             "deliverable": "作品集 + 面试文档",
             "resources": ["本站画像页", "LlamaIndex 官方示例"]},
        ],
        "projects": [
            {"name": "企业知识库问答", "desc": "权限感知、混合检索、答案带引用与置信度，10 万级文档",
             "skills": ["rag", "semantic-search", "reranking", "pgvector", "doc-pipeline"]},
            {"name": "检索评估基准", "desc": "自制 golden set + recall/MRR/忠实度自动回归",
             "skills": ["rag-eval", "llm-eval", "pandas"]},
            {"name": "多模态表格问答", "desc": "PDF 表格抽取与自然语言查询，答案可回溯到单元格",
             "skills": ["doc-pipeline", "multimodal", "chunking"]},
        ],
        "resume_keywords": ["RAG", "向量数据库", "Embeddings", "混合检索", "Rerank",
                            "Chunking 策略", "RAGAS/评估", "pgvector/Qdrant", "知识库",
                            "查询改写", "GraphRAG"],
        "interview": {
            "technical": [
                "BM25 与向量检索各自什么时候失灵？混合怎么融合？",
                "chunk 策略如何影响答案忠实度？举一个你踩过的坑。",
                "重排器带来的收益如何量化？成本呢？",
                "如何评估检索质量而不只是答案质量？",
                "权限过滤放在检索哪一层？为什么？",
            ],
            "system_design": [
                "设计企业知识库：百万文档、多部门权限、日增万篇。",
                "设计一个客服知识库：要求新文档 5 分钟内可问答。",
            ],
            "behavioral": [
                "检索效果差时你的排查顺序是什么？",
                "讲一次用评估数据推动检索架构升级的经历。",
                "业务方要求「必须 100% 准确」你怎么回应？",
            ],
        },
    },

    # ================= AI Infra / MLOps =================
    "mlops": {
        "pitch": "让模型跑得快、跑得省、跑得稳：推理优化、GPU 调度与 LLMOps。数据集显示 vLLM/Triton/CUDA 是稀缺溢价技能。",
        "core_skills": ["docker", "kubernetes", "vllm", "gpu", "inference-opt", "python",
                        "observability", "terraform", "ci-cd", "linux", "quantization"],
        "nice_to_have": ["cuda", "triton-lang", "tensorrt", "distributed-training", "ray",
                         "sglang", "aws", "gcp"],
        "weeks": [
            {"week": 1, "theme": "LLM 推理基础",
             "goals": ["理解 prefill/decode、KV cache、continuous batching",
                        "用 vLLM 起一个 OpenAI 兼容服务并压测",
                        "记录吞吐/延迟/显存基线"],
             "deliverable": "vLLM 服务 + 压测报告（不同并发下的 P50/P99）",
             "resources": ["vLLM 文档", "LLM inference 优化综述（公开博客）"]},
            {"week": 2, "theme": "量化与压缩",
             "goals": ["实操 AWQ/GPTQ/FP8 量化，对比质量与速度",
                        "用 lm-eval 测量化后的能力损失",
                        "输出选型建议（什么场景用什么精度）"],
             "deliverable": "量化对比报告（速度+质量+显存三维度）",
             "resources": ["vLLM quantization 文档", "lm-evaluation-harness"]},
            {"week": 3, "theme": "Kubernetes 上的模型服务",
             "goals": ["写 Helm chart 部署推理服务（GPU 调度、亲和性）",
                        "配置 HPA 与 GPU 利用率监控（DCGM）",
                        "滚动更新与流量切换"],
             "deliverable": "K8s 上的推理服务（一键部署、可回滚）",
             "resources": ["Kubernetes 官方文档", "DCGM Exporter"]},
            {"week": 4, "theme": "观测与成本",
             "goals": ["建立四层监控：GPU/服务/请求/业务",
                        "token 级成本核算与预算告警",
                        "容量规划：从 QPS 推算 GPU 数量"],
             "deliverable": "推理成本模型 + Grafana 看板",
             "resources": ["Prometheus/Grafana", "FinOps for AI 文章"]},
            {"week": 5, "theme": "微调与训练基建",
             "goals": ["跑通 LoRA 微调任务（单卡）并交付为 API",
                        "理解分布式训练概念（DDP/FSDP/DeepSpeed）",
                        "训练任务队列与 checkpoint 管理"],
             "deliverable": "「提交数据→产出可部署 adapter」的自动化管道",
             "resources": ["HF TRL/PEFT", "DeepSpeed 文档"]},
            {"week": 6, "theme": "CI/CD 与评测门禁",
             "goals": ["模型/应用发布流水线：构建→评测门禁→灰度→全量",
                        "推理服务 A/B 与影子流量",
                        "回滚演练"],
             "deliverable": "带评测门禁的 LLMOps 流水线",
             "resources": ["GitHub Actions", "Argo Rollouts"]},
            {"week": 7, "theme": "性能深潜",
             "goals": ["CUDA 基础：写一个向量加法 kernel 并分析瓶颈",
                        "Triton 语言重写同一 kernel",
                        "理解 GPU 架构：SM、显存带宽、occupancy"],
             "deliverable": "kernel 实验笔记（性能曲线+分析）",
             "resources": ["GPU Mode（公开课程/社区）", "Triton 教程"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["作品集：推理优化案例（前后数据）+ K8s 部署仓库",
                        "简历对齐：vLLM/K8s/量化/成本",
                        "面试演练：设计支撑 1万 QPS 的推理平台"],
             "deliverable": "作品集 + 面试文档",
             "resources": ["本站画像页", "vLLM GitHub discussions"]},
        ],
        "projects": [
            {"name": "推理服务优化实战", "desc": "开源自模型经量化+调参，吞吐提升 X%、成本降 Y%",
             "skills": ["vllm", "quantization", "inference-opt", "observability"]},
            {"name": "K8s 推理平台模板", "desc": "Helm 一键部署 GPU 推理服务，含 HPA/监控/灰度",
             "skills": ["kubernetes", "terraform", "ci-cd", "gpu"]},
            {"name": "LoRA 训练到上线管道", "desc": "数据→训练→评测门禁→自动部署 adapter",
             "skills": ["lora", "fine-tuning", "llm-eval", "docker"]},
        ],
        "resume_keywords": ["vLLM", "Kubernetes", "GPU 调度", "推理优化", "量化（AWQ/GPTQ）",
                            "LLMOps", "Terraform", "可观测性", "成本优化", "LoRA 训练管道",
                            "CI/CD 门禁"],
        "interview": {
            "technical": [
                "解释 KV cache 显存占用公式；长上下文服务的瓶颈在哪？",
                "continuous batching 为什么能提升吞吐？代价是什么？",
                "INT8/FP8/AWQ 各适合什么场景？如何验证量化没伤模型？",
                "GPU 利用率高但吞吐低，可能是什么问题？",
                "设计一个推理服务的容量规划方法。",
            ],
            "system_design": [
                "设计支撑 1 万 QPS 的 LLM API 平台：多模型、多租户、成本分摊。",
                "设计训练平台：GPU 队列、checkpoint、故障恢复。",
            ],
            "behavioral": [
                "讲一次线上推理服务事故（OOM/超时）与根治过程。",
                "如何在成本与延迟之间做工程决策？举实例。",
                "研发不想接评测门禁，你怎么推进？",
            ],
        },
    },

    # ================= AI 产品经理 =================
    "ai-pm": {
        "pitch": "定义 AI 该做什么、做到什么程度：场景选择、评估标准与不确定性管理。懂 eval 的 PM 最稀缺。",
        "core_skills": ["product-management", "llm-fundamentals", "prompt-engineering",
                        "llm-eval", "user-research", "analytics", "rag", "ab-testing",
                        "customer-facing"],
        "nice_to_have": ["prototyping", "sql", "structured-output", "guardrails", "gtm"],
        "weeks": [
            {"week": 1, "theme": "AI 产品直觉",
             "goals": ["深度使用 10 个 AI 产品，各写一页拆解（场景/差异/短板）",
                        "理解 LLM 能力边界：能/勉强/不能三清单",
                        "掌握 token 成本与延迟对产品形态的影响"],
             "deliverable": "AI 产品拆解集 + 机会假设清单",
             "resources": ["各大模型官方产品文档", "Lenny's Newsletter AI 篇目"]},
            {"week": 2, "theme": "用例挖掘与优先级",
             "goals": ["用 JTBD 访谈 5 个目标用户，记录 AI 接受度",
                        "输出用例评分卡：价值/可行性/风险/成本",
                        "选定一个练手用例"],
             "deliverable": "用例评估文档（含被砍掉的选项与理由）",
             "resources": ["JTBD 访谈指南", "本站技能数据（需求侧验证）"]},
            {"week": 3, "theme": "原型与提示词",
             "goals": ["用 prompt + 无代码/Streamlit 搭出可点原型",
                        "学会写结构化提示词并做 3 轮迭代",
                        "记录「提示词即 PRD」的写法"],
             "deliverable": "可演示原型（真实用户试玩反馈 5 份）",
             "resources": ["Anthropic/OpenAI prompt 指南", "Streamlit"]},
            {"week": 4, "theme": "评估标准（PM 的核心武器）",
             "goals": ["定义质量维度：准确/有用/安全/延迟，各给量化标准",
                        "建 30 条黄金集，组织人工评审",
                        "把「AI 输出验收」写进 PRD"],
             "deliverable": "AI 功能验收标准文档（可直接用于研发）",
             "resources": ["RAGAS/eval 框架文档", "Hamel Husain evals 博文"]},
            {"week": 5, "theme": "PRD 与技术协作",
             "goals": ["写一份 AI 功能 PRD：含不确定性、降级、兜底策略",
                        "与（模拟）工程师对齐：检索/模型/评估三件事",
                        "理解 RAG vs 微调 vs 提示词的产品级取舍"],
             "deliverable": "完整 PRD + 技术方案评审纪要",
             "resources": ["本站画像与技能数据", "内部模板（自建）"]},
            {"week": 6, "theme": "指标与实验",
             "goals": ["设计北极星与护栏指标（采纳率/人工修正率/投诉率）",
                        "设计 A/B 实验与样本量估算",
                        "埋点方案与看板"],
             "deliverable": "指标体系 + 实验方案",
             "resources": ["产品分析（Amplitude/GA4）文档", "A/B 测试指南"]},
            {"week": 7, "theme": "风险、合规与信任",
             "goals": ["梳理幻觉/隐私/偏见三类风险与缓解",
                        "设计用户信任机制：来源引用、置信度、反馈闭环",
                        "了解 GDPR/AI Act 对产品的影响面"],
             "deliverable": "AI 功能风险评估与信任设计文档",
             "resources": ["NIST AI RMF 摘要", "EU AI Act 概览"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["作品集：案例研究（问题→方案→评估→数据）",
                        "简历对齐画像页关键词",
                        "面试演练：产品案例分析题"],
             "deliverable": "案例集 + 面试准备",
             "resources": ["本站画像页", "PM 案例面试框架"]},
        ],
        "projects": [
            {"name": "AI 功能从 0 到 1 案例研究", "desc": "完整走一遍用例→原型→评估→指标，产出全套文档",
             "skills": ["product-management", "llm-eval", "prompt-engineering"]},
            {"name": "AI 功能验收标准模板", "desc": "可直接复用的黄金集+评审流程+PRD 模板",
             "skills": ["llm-eval", "user-research"]},
            {"name": "竞品 AI 能力拆解报告", "desc": "用统一框架拆 5 个竞品的 AI 功能与差距",
             "skills": ["analytics", "customer-facing"]},
        ],
        "resume_keywords": ["AI 产品经理", "LLM 功能设计", "评估标准/Evals", "Prompt 设计",
                            "RAG 产品化", "A/B 实验", "用户研究", "AI 风险与合规",
                            "北极星指标", "人机协同"],
        "interview": {
            "technical": [
                "给一个 AI 功能定义「上线标准」，你会设置哪些量化门槛？",
                "RAG 和微调在产品成本/迭代速度上的差异？",
                "幻觉率降到多少可以上线？取决于什么？",
                "如何设计让用户信任 AI 输出的交互？",
                "延迟 3 秒对你会做什么产品取舍？",
            ],
            "case_design": [
                "为 Notion 设计一个 AI 功能：从用户痛点到验收标准。",
                "电商平台要用 AI 做售后客服，写出指标体系与上线计划。",
            ],
            "behavioral": [
                "工程师说「模型就是这个水平」，你怎么推进质量提升？",
                "讲一次你砍掉 AI 功能的经历与判断依据。",
                "如何管理老板对 AI 能力的过度预期？",
            ],
        },
    },

    # ================= 数据工程（AI 方向） =================
    "data-eng": {
        "pitch": "AI 的一切始于数据：管线、质量与检索底座。向量数据与非结构化数据工程是新溢价点。",
        "core_skills": ["python", "sql", "etl", "warehouse", "airflow", "docker",
                        "doc-pipeline", "embeddings", "vector-db", "data-curation"],
        "nice_to_have": ["spark", "kafka", "dbt", "rag", "aws", "observability", "pgvector"],
        "weeks": [
            {"week": 1, "theme": "现代数据栈速览",
             "goals": ["搭建本地环境：Python+SQL+DuckDB/Postgres",
                        "实现一个小型 ETL：API→清洗→数仓表",
                        "掌握数据建模基础（维度/事实）"],
             "deliverable": "端到端小管线 + 数据字典文档",
             "resources": ["DuckDB 文档", "dbt Fundamentals（免费课）"]},
            {"week": 2, "theme": "编排与调度",
             "goals": ["用 Airflow 重写管线：DAG、重试、告警",
                        "增量抽取与幂等设计",
                        "数据质量检查（行数/空值/新鲜度）"],
             "deliverable": "带告警的调度管线（失败自动通知）",
             "resources": ["Airflow 官方教程", "Great Expectations"]},
            {"week": 3, "theme": "非结构化数据接入",
             "goals": ["批量解析 HTML/PDF 为结构化文本",
                        "去重（哈希+模糊）、清洗、PII 处理",
                        "为下游 embedding 准备语料"],
             "deliverable": "百万级文本语料库（可复现构建）",
             "resources": ["trafilatura/Unstructured", "PII 处理实践"]},
            {"week": 4, "theme": "向量数据工程",
             "goals": ["embedding 批处理管道（分片/断点续跑/成本核算）",
                        "pgvector/Qdrant 的索引与更新策略",
                        "向量数据版本化"],
             "deliverable": "可增量更新的向量索引管道",
             "resources": ["pgvector 文档", "Qdrant 批量导入指南"]},
            {"week": 5, "theme": "流与实时",
             "goals": ["用 Kafka/Flink 或轻量替代实现准实时入库",
                        "变更数据捕获（CDC）概念与实操",
                        "为 RAG 设计「新文档 5 分钟可检索」"],
             "deliverable": "准实时的检索底座 demo",
             "resources": ["Kafka 基础教程", "Debezium CDC"]},
            {"week": 6, "theme": "AI 时代的数据质量",
             "goals": ["为训练/RAG 语料定义质量指标（重复率/毒性/许可）",
                        "合成数据的生成与验证",
                        "血缘追踪：从答案回溯到源文档"],
             "deliverable": "语料质量报告模板 + 血缘方案",
             "resources": ["数据质量框架文章", "OpenLineage"]},
            {"week": 7, "theme": "云上架构",
             "goals": ["在 AWS/GCP 部署整套管线（IaC）",
                        "成本监控与优化（存储/计算分离）",
                        "安全：最小权限与加密"],
             "deliverable": "云上可复现的数据平台（Terraform）",
             "resources": ["Terraform 教程", "云厂商免费层"]},
            {"week": 8, "theme": "求职冲刺",
             "goals": ["作品集：数据平台仓库 + 架构图 + 成本数据",
                        "简历对齐画像关键词",
                        "面试演练：设计 RAG 数据底座"],
             "deliverable": "作品集 + 面试文档",
             "resources": ["本站画像页", "DataTalks.Club 课程"]},
        ],
        "projects": [
            {"name": "RAG 数据底座", "desc": "文档→清洗→embedding→向量库 全自动管线，含血缘与质量报告",
             "skills": ["etl", "doc-pipeline", "embeddings", "pgvector"]},
            {"name": "实时检索索引", "desc": "CDC + 增量索引，新数据 5 分钟可查",
             "skills": ["kafka", "airflow", "vector-db"]},
            {"name": "语料质量流水线", "desc": "去重/许可/毒性检查，产出可训练语料集",
             "skills": ["data-curation", "pandas", "python"]},
        ],
        "resume_keywords": ["数据管线", "Airflow", "向量数据工程", "Embeddings 批处理",
                            "pgvector", "数据质量", "CDC/实时", "数仓建模", "Terraform",
                            "非结构化数据", "成本优化"],
        "interview": {
            "technical": [
                "幂等的增量 ETL 怎么设计？失败重跑会发生什么？",
                "embedding 批处理如何断点续跑与控成本？",
                "向量库的索引更新策略：全量重建 vs 增量，如何选？",
                "如何为 RAG 语料定义并监控质量？",
                "列式存储为什么快？什么场景不适用？",
            ],
            "system_design": [
                "设计日增百万文档的知识库数据底座。",
                "设计训练数据平台：版本化、血缘、质量门禁。",
            ],
            "behavioral": [
                "数据出错导致下游模型变差，如何复盘与预防？",
                "讲一次你用自动化替代人肉运维管线的经历。",
                "数据团队与算法团队优先级冲突怎么处理？",
            ],
        },
    },
}

# 画像叙述（建站用，1-2 句，基于数据 + 公认事实，不编造具体数字）
PROFILE_INTROS = {
    "llm-app": "数据集里出现最频繁的工程师岗位。招聘方要的核心不是「会调 API」，而是把 LLM 做成可靠功能的能力：结构化输出、RAG、评估与成本控制。",
    "agent": "2025-2026 增长最快的方向，从 Agent 框架关键词（LangGraph/MCP/多智能体）的高频出现可见一斑。核心考察工具调用可靠性、编排设计与护栏。",
    "rag": "很少有职位标题直接叫 RAG 工程师，但大量 LLM 应用岗把 RAG 列为核心要求（本数据集 RAG 技能溢价 +11.1%）。本质是「检索质量工程师」。",
    "mlops": "推理服务与 GPU 效率是稀缺技能带：vLLM、Kubernetes、量化、CUDA 在语料中频次不高但溢价明显。适合有基建背景的工程师切入。",
    "ai-pm": "AI 产品岗的门槛已从「懂概念」升级为「会定义评估标准」。黄金集、验收指标、人机协同设计是差异化能力。",
    "data-eng": "AI 的数据底座工程师：非结构化数据处理与向量数据工程是传统数据工程的新增溢价面，管线与质量纪律仍是基本功。",
}


def gap_analysis(background_id: str, user_skills: list[str], role_id: str) -> dict:
    """缺口 = core − 已有（按数据频次排序在 analyze 侧补充），已有但不在 core 的列入加分项。"""
    route = ROUTES[role_id]
    base = set(BACKGROUNDS.get(background_id, {}).get("base_skills", []))
    have = set(user_skills) | base
    core = list(route["core_skills"])
    missing = [s for s in core if s not in have]
    extra = [s for s in have if s not in core]
    return {"missing": missing, "ready": [s for s in core if s in have], "bonus": extra}
